[package]
name = "sap-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1"
thiserror = "1"

[build-dependencies]
cxx-build = "1"
